### ISSUE TITLE
Certificate qr.evnotify.de expired

### ISSUE THREAD

**Issue by martijns** [EVNotify/EVNotify#149]
### New issue
- Short description:
The certificate for https://qr.evnotify.de has expired on 4th of April. This URL is used in the QR codes generated by the app.

- Can you reproduce it? (_If so, how?_):
Visit https://qr.evnotify.de

- [x] critical issue? (_issue, which will affect multiple accounts, 
  an issue which prevents that you can use the app in a normal way,
  bug which makes app unusable, security breach*_) (Yes/No):
  
 <details>
  <summary>additional information</summary>
  

  (_such as AKey [**NEVER EVER SHARE YOUR TOKEN!**], images_ or debug data from overview -> debug icon, your phone and android version)

</details>

\* **For very critical security breaches, please mail directly at info@evnotify.de**

**Comment by GPlay97** [comment]
Thanks. My bad. The auto-renewal didn't work for some reason.

This has been fixed.
