### ISSUE TITLE
Charging data Kona EV not correct

### ISSUE THREAD

**Issue by matthiaslink77** [EVNotify/EVNotify#152]
### New issue
- Charging data Kona EV not correct
- Detailed description:
Hyundai Kona EV charging screen (page 3) shows:
Battery current: -3.10A
Charge-/Discharge power: -1,26kW

Car is charging with 8A and approx. 1.7 kW

Estimated range also does not show the actual vehicle information.
App shows
![IMG_4367](https://user-images.githubusercontent.com/12761754/57199798-97d18380-6f83-11e9-9b23-468212df6d07.jpg)
![IMG_4368](https://user-images.githubusercontent.com/12761754/57199799-986a1a00-6f83-11e9-8c0e-6f8143145e28.jpg)

 350/365 km, while car shows already > 400 km range at 96 % charge.

- Can you reproduce it? (_If so, how?_):
Yes. Just connect app and read data.

- [ ] critical issue? (_issue, which will affect multiple accounts, 
  an issue which prevents that you can use the app in a normal way,
  bug which makes app unusable, security breach*_) (Yes/No): No
  
 <details>
  <summary>additional information</summary>
  

  (_such as AKey [**NEVER EVER SHARE YOUR TOKEN!**], images_ or debug data from overview -> debug icon, your phone and android version)

</details>

\* **For very critical security breaches, please mail directly at info@evnotify.de**

**Comment by GPlay97** [comment]
Hey,

thank you for contributing your first issue and the detailed information.

The charging data seems to be wrong in this case. On slack, another user faced a similar issue while charging on AC type2.

To inspect this, can you enable "debug mode" (press the little bug icon on the top) and let it enabled for a few seconds, while it fetches data from the car via Bluetooth. Enable it, when this happens again (should be reproducable).

This could help a lot. Then send me your data - either here - or via mail info(at)evnotify.de.

The range is just estimated based on the consumption you entered, in your case 17.5kWh/100km. Just simple maths currently, no "real data" or intelligent algorithms yet.

**Comment by GPlay97** [comment]
After investigating, it comes out, that this is actually the battery data from OBD.

In your example -> 404,9V * 3,1A = 1255,19 W => 1,25519kW.

So actually this is not a bug, it's a feature ;)

Thanks also to @EVSalomon for finding out :)
