### ISSUE TITLE
Can't create new account in app

### ISSUE THREAD

**Issue by maulwuff** [EVNotify/EVNotify#154]
### New issue
- Short description: 
App responds with `unexpected error` when hitting next on the password dialog. 

- Detailed description:
Enter password twice in the registration process and hit next. `Create account` label will turn red and show `unexpected error` beneath it. 

- Can you reproduce it? (_If so, how?_):
Try any password, as long as they match. 

- [x] critical issue?  (Yes/No): yes, prevents creating new accounts. 
  
Happens with Version from 03.2019 and betra from 05.2019

Android 8.1.0

**Comment by GPlay97** [comment]
Hey,

this is currently a problem with the server. I'm working on it. Sorry for the circumstances. You can have a look at status.evnotify.de for more information.

**Comment by maulwuff** [comment]
Oh, ok. Then I'll try tomorrow. (Thought I could have a nice evening with my e-niro in the garage, playing around with evnotify 🤣)

**Comment by GPlay97** [comment]
I'm very sorry for this!

**Comment by GPlay97** [comment]
All services are up and running again. Sorry for the trouble!

**Comment by maulwuff** [comment]
Hm, still doesn't work, with the same error as yesterday. Status page says, everything is green.

**Comment by GPlay97** [comment]
Since it was a DNS issue, it can take some time, until it's updated to everyone. Can you completely close the app, restart your phone and then try again? I tried to register new accounts, it works fine here.

**Comment by maulwuff** [comment]
Is there a way to get a more detailed error message? I rebooted, tried wifi and cellular, uninstalled from beta to main release, tried in airplane mode to see what happens, but it always fails.

**Comment by GPlay97** [comment]
Hm, normally an unexpected error message comes, when it can't be handled.

For further inspection, can you send me a mail to info@evnotify.de together with your AKey? Maybe I can find something out.

**Comment by maulwuff** [comment]
Where can I find an Akey when I've not registered, yet? It fails on the second screen of creating an account.

**Comment by GPlay97** [comment]
You are right.

Then just mail with exact details what you enter and where. 
Maybe attach also screenshots in mail.
Thanks.

**Comment by maulwuff** [comment]
:-) just edited my last comment with  screenshot.

**Comment by GPlay97** [comment]
No,because I can't reproduce it.

Are you in WiFi? Maybe try with mobile data. Furthermore - just for testing - try a password 123456 or so (at least 6 digits).
But please send a mail, this is better to get more information

**Comment by maulwuff** [comment]
Make sure to not block the app in your firewall....
