### ISSUE TITLE
Crash on Xperia Active

### ISSUE THREAD

**Issue by maulwuff** [EVNotify/EVNotify#155]
- Short description: 
App crashes on startup on a Xperia Active phone

- Detailed description:
Sony Ericsson Xperia active Smartphone (7,6 cm, 3" screen) runs on cyanogenmod 10 (2013.10.06 nightly) (which is Android 4.1.2) so I thought evNotify may work.
EvNotify is 2.0.9  It may be the beta version like on my main phone, as it shows the same version number in android settings. This old play store version doesn't have betatester tab or hints :-( 

The startscreen appears, but when the help popups from the guided tour appear, the app crashes. "Bericht"/report vanishes too fast to tap it, it is also greyed out.

Do you think there is a chance to get it running on this tiny old phone? would be perfect for the cars center console.
 
oh, I just managed to click the report button ;) I'll send the feedback.

**Comment by GPlay97** [comment]
Unfortunately Android 4 is now so old that support is super hard. 
It can not be guaranteed that every functionality works. 
Due to new restrictions and conditions for new APIs, Android 4 will also no longer be supported in the future.
