### ISSUE TITLE
e-Niro misses CEC and CED

### ISSUE THREAD

**Issue by maulwuff** [EVNotify/EVNotify#165]
I have a e-Niro and when I choose this as vehicle in the app, CEC and CED are missing (shows 0).
When I use Kona, all fields are filled. 
Something seems to be wrong in the e-Niro profile, which should be the same as in Kona ;-)

v2.1.0:03

**Comment by GPlay97** [comment]
Will be available soon

**Comment by ektus** [comment]
How soon is "soon", especially on Android?

**Comment by GPlay97** [comment]
https://github.com/EVNotify/EVNotify/issues/166#issuecomment-599259624

**Comment by GPlay97** [comment]
@ektus @maulwuff 
Sorry for the huge delay. App build works again..

It was implemented. If you still encounter issues, let me know in a new issue.

**Comment by ektus** [comment]
I've got the update, and it looks good now with my 2019 e-Niro. No more need to spoof Kona :-)
