### ISSUE TITLE
Dongle links broken

### ISSUE THREAD

**Issue by SiGmAX666** [EVNotify/EVNotify#168]
All of the Amazon links are broken for me except for two, one of which is no longer available (iCar Bluetooth OBD2) and the other is very expensive (KONNWEI KW902-BLACK KW902).

**Comment by GPlay97** [comment]
Thanks. You are right!

I will fix them later

**Comment by GPlay97** [comment]
I added two new available dongles that seems to work quite good.

However, most of the dongles are still not available :( Hopefully they will be available again soon!
