### ISSUE TITLE
OBDLink MX+ not showing up in Setup, Devices on iOS

### ISSUE THREAD

**Issue by ColoradoNate** [EVNotify/EVNotify#170]
### New issue
- Short description: Bluetooth-connected OBDLink MX+ does not show up in settings, devices
- Detailed description:

- Can you reproduce it? YES:
1. Plug in the OBDLink MX+ to vehicle
2. On iOS Settings/Bluetooth, connect to "OBDLink MX+ 12234" (succeeds)
3. Install EVNotify
4. Create login
5. Go to Settings of EVNotify, under "Devices", "OBDII-Device"
BUG: nothing shows up in the drop-down

- [ ] critical issue? (_issue, which will affect multiple accounts, 
  an issue which prevents that you can use the app in a normal way,
  bug which makes app unusable, security breach*_) (Yes/No):
  
 <details>
 <summary>additional information</summary>
iOS 13.3
Tried on iPad Air (3rd generation) and iPhone 11 Pro Max
</details>

**Comment by GPlay97** [comment]
For iOS, only one dongle is supported (unfortunately this one is no longer available to buy currently).

In the current application setup it's unlikely that more variants are supported within iOS.

For a wide support you would need to switch to Android - which is by the way heavily more stable and tested. Or wait for a full application rewrite.
