### ISSUE TITLE
Create a more condensed app overview

### ISSUE THREAD

**Issue by maulwuff** [EVNotify/EVNotify#171]
Currently, the things shown on the dashboard are too tall, to fit on a 5.x inch screen. That's a lot of wasted space.
Are you interested in some ideas to get the information on screen without the need of scrolling?
Hm, I'll just start right away ;-)
- Show SOC as bar instead of circle
- Use more display style like currenlty for temps: a / b / c
- hide long names behind the symbols as toast or something
- Group 1
    - SOC-display / SOC-bms
    - current values kW, km 
    - CEC / CED  
- group 2: HV battery:
    - Volts / Amps
    - Temps
    - SOH
- group 3: AUX battery.
    - Voltage

**Comment by GPlay97** [comment]
Due to work on v3 and complete new design (and themes) this will be closed.  If then still a thing, new issue will be created.
