### ISSUE TITLE
Kia e-Soul support missing

### ISSUE THREAD

**Issue by gidhap** [EVNotify/EVNotify#172]
### New issue
- Short description:  Kia e-Soul support missing
- Detailed description: I just downloaded the app, but unfortunately my Kia e-soul is not listed (yet?)
And...great job, appreciate your efforts, will use the "donate" button ;o)
Last not least, if you need somebody testing with a Kia E-Soul 2019 (not the Soul EV) I am happy to support. 

- Can you reproduce it? (_If so, how?_): 

- [ ] critical issue? (_issue, which will affect multiple accounts, 
  an issue which prevents that you can use the app in a normal way,
  bug which makes app unusable, security breach*_) (Yes/No):
  
 <details>
  <summary>additional information</summary>
  

  (_such as AKey [**NEVER EVER SHARE YOUR TOKEN!**], images_ or debug data from overview -> debug icon, your phone and android version)

</details>

\* **For very critical security breaches, please mail directly at info@evnotify.de**

**Comment by noradtux** [comment]
You could try to select the Kona in EVNotify. So far Kona, e-Niro and Ioniq FL behave the same. If Kona works for you adding support for the e-Soul should be trivial.

**Comment by gidhap** [comment]
Txs, I'll try as soon as my OBD adapter has arrived

**Comment by GPlay97** [comment]
@noradtux @gidhap 
It was confirmed, that it works with the Kona recently!

It will be officially added in the next update!

**Comment by GPlay97** [comment]
Added.

Will be live in the update published later.
