### ISSUE TITLE
Amazon link for Apple compatible OBD2 dongle doesn't work

### ISSUE THREAD

**Issue by Razzertaz** [EVNotify/EVNotify#179]
As the title says, the link seems to be broken. It's on this page in the wiki: https://github.com/EVNotify/EVNotify/wiki/Compatibility.
I guess the dongle has been removed. Do you have the name of the dongle so I can try and find it somewhere else?

**Comment by GPlay97** [comment]
It should be this one: https://amzn.to/37gRGCu
