### ISSUE TITLE
Request: Configurable Units

### ISSUE THREAD

**Issue by bjg222** [EVNotify/EVNotify#196]
- Short description: Please add ability to configure the units of values shown in the app
- Detailed description: EVNotify shows all values in metric by default.  For users in the US, please include customary units (ie, miles, degrees Fahrenheit, etc.).  In addition, different makes report efficiency different, so please include various options here, such as mi/kwh (How my car, the Kona EV reports it), kwh/100mi, km/kwh, or kwh/100km.

**Comment by chrisg30** [comment]
+1

**Comment by GPlay97** [comment]
I'm currently developing this suggested feature in v3 app (and backend). v3 repo is currently still private, but testing phases will be expanded in the next weeks ( I will give out official infos soon how to contribute then).

I will close this here on the v2 repo now, thanks for suggestion!
