### ISSUE TITLE
Problems with charging monitoring

### ISSUE THREAD

**Issue by konatpf** [EVNotify/EVNotify#211]
### New issue
- Short description: since about 2 weeks I cannot Monitor the Charging 
- Detailed description: charging started as normal (kona), but no information shown in the app. Last charging the information in the app was shown. But stopped after 2 hours.  Now no information in the app. Dongl bought directly here. AKey C563b6
Pls help, was main reason for buying. Thanks

PS. Telegram and Mail notifikation never worked. 

- Can you reproduce it? (_If so, how?_):

- [ ] critical issue? (_issue, which will affect multiple accounts, 
  an issue which prevents that you can use the app in a normal way,
  bug which makes app unusable, security breach*_) (Yes/No):
  
 <details>
  <summary>additional information</summary>
  

  (_such as AKey [**NEVER EVER SHARE YOUR TOKEN!**], images_ or debug data from overview -> debug icon, your phone and android version)

</details>

\* **For very critical security breaches, please mail directly at info@evnotify.de**

**Comment by GPlay97** [comment]
Sounds like a warranty issue, that we need to discuss via mail. Please write to info@evnotify.de

For notifications, a big update for PnP will be rolled out soon, that increases reliabilty.
