### ISSUE TITLE
Skoda Enyaq support

### ISSUE THREAD

**Issue by aslten** [EVNotify/EVNotify#238]
### New feature request
- Add support for Skoda Enyaq
- As the Enyaq shares its platform with the ID.x cars it is probably possible to use their integration as a starting point.

\* **For very critical security breaches, please mail directly at info@evnotify.de**

**Comment by GPlay97** [comment]
Have you tried using the Id3 profile? Does it have valid data for you?

**Comment by fredrikedling** [comment]
No actually not. I just got the Enyaq a couple a days ago. I am planning to buy the hardware for the EvNotify but first wanted to check if it is on the roadmap to implement it. 
But if you think that the Id.3 profile can work I can test it and give you feedback. Maybe also help out with testing the integration.
    Den onsdag 5 maj 2021 09:40:52 CEST, GPlay97 ***@***.***> skrev:  
 
 


Have you tried using the Id3 profile? Does it have valid data for you?

**Comment by HabibA007** [comment]
I use the ID4 77 Profile to use it with my Enyaq 80 and it works very well. Why you don’t copy the profile to an enyaq profile? The next step is to support abrp with an enyaq… I have to use there also the id4 profile and the developer of abrp answered me he will support the enyaq live track even EVNotify support it… can you support the enyaq nativly?

**Comment by starskyman** [comment]
> ### New feature request
> * Add support for Skoda Enyaq
> * As the Enyaq shares its platform with the ID.x cars it is probably possible to use their integration as a starting point.
> 
> * **For very critical security breaches, please mail directly at [info@evnotify.de](mailto:info@evnotify.de)**

I have seen that the ID3 works with the Skoda Enyaq - I don’t have the ID3 option in the app.

**Comment by GPlay97** [comment]
Added in #259
