### ISSUE TITLE
Supported Android Version

### ISSUE THREAD

**Issue by RalphS69** [EVNotify/EVNotify#239]
### New issue
- Critical issue!
- according to the [EVNotify web site](https://evnotify.de/), Android 4.1 is required
- according to the [play store](https://play.google.com/store/apps/details?id=com.evnotify.app&hl=en_US&gl=US), Android 4.4 is required

#### Hardware / Software:
- Samsung Galaxy S3 mini GT-I8200N with Android 4.2.2

 <details>
 <summary>Trusting the information on the web site I managed to get a used Galaxy S3 mini - just to find out the hard way, that a higher Android version seems to required. </summary>

Quote from the web site:

> What do I need for EVNotify?
>Download the app on the Google Play Store. You currently need an Android device with at least Android 4.1 installed, Android 6 or later is recommended. Furthermore you need a bluetooth-capable OBDII-dongle. To retrieve the data you can simply use another device with EVNotify or use the web interface (compatible with any device).

Quotes from the Play Store

> runs on all android-capable devices (even Android TV-Sticks) [Android >= 4.1]

> Requires Android; 4.4 and up

</details>

**Comment by GPlay97** [comment]
You are right, need to adjust that. Google recently changed the required SDK, thanks for the information. However, even if it might work with Android 4.4, Android 6 or later is still recommended, since it's already really really old Android 4

**Comment by RalphS69** [comment]
This is somewhat unfortunate. On my iPhone the app did not work beforehand (see https://github.com/EVNotify/EVNotify/issues/215) and now it crashes (see https://github.com/EVNotify/EVNotify/issues/240), thus I tried to get up and running with a used Android phone ... now this seems to be too old. ):

Note: Please also adjust the system requirements on on this site: https://github.com/EVNotify/EVNotify/wiki/Compatibility

**Comment by GPlay97** [comment]
Yes, I'll have a look at it. Android 4 is like Internet Explorer 8 or older, so always hard ^^
