### ISSUE TITLE
Logdatei

### ISSUE THREAD

**Issue by Elculione** [EVNotify/EVNotify#244]
I want to save the log from app.EVNotify.de. I can read 

{"id":337823,"akey":"*****","start":1620964744,"end":1620966004,"charge":0,"autogenerated":1,"title":"14.05.2021 05:59:04","archived":0},

but nothing more.
cant find any dokumentation or something.

**Comment by GPlay97** [comment]
If it is still a thing, there is a /logdetail endpoint (in the current API). If you need more help, I can assist you within mail (info@evnotify.de)
