### ISSUE TITLE
Does OBDLink MX+ work on iOS?

### ISSUE THREAD

**Issue by mrubioroy** [EVNotify/EVNotify#245]
OBDLink MX+ is certified “Made for iPhone”. Probably the only Bluetooth (not LE) working on iOS.
Does it work with EVNotify on iOS?
Is EVNotify for iOS only available on TestFlight?
What are the advantages of using Bluetooth vs Bluetooth LE?

**Comment by mrubioroy** [comment]
I've tested and it doesn't.

I see there's a Cordova plugin that would allow the connection to "Made for iPhone" classic Bluetooth accessories on iOS:
https://github.com/stevef51/cordova-ios-external-accessories

The API is similar to BluetoothSerial.

**Comment by GPlay97** [comment]
The new app generation, v3, that is under active development, as mentioned now in the README, supports a lot (if not all) dongles , even under iOS. v2 only works with limited dongles unfortunately.
