### ISSUE TITLE
Question Enyaq

### ISSUE THREAD

**Issue by PSKOD** [EVNotify/EVNotify#246]
I would like to ask if is suported Enyaq.

**Comment by GPlay97** [comment]
You can choose ID3 profile currently, a dedicated one will be added in the upcoming days

**Comment by HabibA007** [comment]
Upcoming weeks? Month?
I know it‘s a free project but when you promise something and nothing happens its very frustrating and possibly blocks other developers who think there is already a working project here

**Comment by GPlay97** [comment]
Added now in #259
