### ISSUE TITLE
Data log automation

### ISSUE THREAD

**Issue by CarlosAF72** [EVNotify/EVNotify#253]
Hi, I would like to automatically start the logging for each drive. So whenever I open ev notify it should start logging the  ride. Currently I have sometimes issues to start the logging. I just started using the app so maybe I haven't found the right way to do it.

**Comment by GPlay97** [comment]
To be able to automatically log drives, you have to enable location synchronization. Ensure it's enabled in EVNotify and within system settings of your phone (requires high precision mode). After drive (at least a few minutes, at least 5), it's shortly created afterwards.

**Comment by iGadget** [comment]
I can't seem to get this working. I've enabled local synchronization, but I'm never getting anything in the logs. Not in Charges, not in Drives and not in Statistics. What am I doing wrong?

**Comment by GPlay97** [comment]
If requirements are met (a couple of minutes of transferring data), the log should be created automatically after a couple of minutes. For driving logs, it is currently important to enable high precision, so location data can be retrieved.

You can also write a mail with your akey to info(at) evnotify.de, so I can have a look at it. Just then send me a date, where you charged for example.
