### ISSUE TITLE
Egolf Support iOS version

### ISSUE THREAD

**Issue by amnesia106** [EVNotify/EVNotify#268]
I would love if EVNotify would support the vw egolf on ios version as well.

only Hyundai and the follow cars are available 
![EB8328E9-4713-47F8-9C79-F127E1B44ABC](https://user-images.githubusercontent.com/40226796/133858210-9a815f2c-a1f7-46c6-a7cb-8e2851145c9a.jpeg)

**Comment by NarkoKrig** [comment]
E-Golf in generel I miss it on Android. :)

**Comment by johannestax** [comment]
+1 for e-Golf

**Comment by GPlay97** [comment]
E Golf integration was implemented. A better integration will be added within v3, as mentioned in README.
