### ISSUE TITLE
Release current android app on google play

### ISSUE THREAD

**Issue by carefulcomputer** [EVNotify/EVNotify#272]
The version on google play is old and doesn't have e-golf. Can you please release current code on google play ?

**Comment by GPlay97** [comment]
Code is always up to date. Do you mean the binary APK?

**Comment by GPlay97** [comment]
Or on play store itself? For this, you need to join beta tester program directly on play store. You can do this by your own

**Comment by carefulcomputer** [comment]
Thanks. I meant play store.
Do you have any estimated timeline for production release of app ?
