### ISSUE TITLE
Can't relink to ABRP

### ISSUE THREAD

**Issue by Midyr2** [EVNotify/EVNotify#278]
Hello,

I've unlink the connection within ABRP to evnotify.

Now it is impossible to reconnect.

evnotify says is is connected(I also unlink, link again) But in ABRP I alway shows the connection windows.

 I also ask ABRP support, they ask me to connect you...

How can I sole it?

 
Thanks

Frank

**Comment by freechelmi** [comment]
I seem to have the same problem , when you unlink , relinking seems impossible

**Comment by GPlay97** [comment]
One way would be to message me via info@evnotify.de - I can then manually reset the connection from the database
