### ISSUE TITLE
[Question] How to use Bluetooth Low Energy ODB2 dongle?

### ISSUE THREAD

**Issue by kovadam69** [EVNotify/EVNotify#279]
Hi!

I was searching here and on the internet but found 0 information about how to connect a Bluetooth Low Energy dongle with EVNotify. It only lists Bluetooth devices I paired with the phone, but since this is a Low Energy Bluetooth device, it cannot be paired with the phone, however it is therefore also not listed in the paired Bluetooth device list.

I can use this dongle with LeafSpy Pro (for Leaf) and with Torque Pro (for Opel Ampera-E (chevy bolt)) without any issues, however they had the option to use BLE device, and they were searching for it separately, not using the op. system's Bluetooth list.

How can I use BLE device with EVNotify?

OP: Android 12
Phone: Samsung Galaxy S20+

Thanks!

kovadam

**Comment by GPlay97** [comment]
On the current v2 version, EVNotify only supports Bluetooth Classic Dongles under Android. Within v3, the next app generation, as mentioned now in the README, it is possible to connect with BLE Dongles , even under android.
