### ISSUE TITLE
Certificate on qr.evnotify.de expired

### ISSUE THREAD

**Issue by schnism** [EVNotify/EVNotify#309]
Hi!

The Lets Encrypt Certificate on qr.evnotify.de has expired on beginning of December:

```
❯ curl -v  https://qr.evnotify.de
* Server certificate:
*  subject: CN=qr.evnotify.de
*  start date: Sep  7 18:22:58 2023 GMT
*  expire date: Dec  6 18:22:57 2023 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3

```

This seems to be on a dedicated server at Hetzner, so if you need help with setting up auto renewal with certbot just let me know.

**Comment by GPlay97** [comment]
Thank you for the report and sorry for the inconveniences. Indeed it was not automatically renewed,  I fixed it shortly after your report.

Thanks again
