### ISSUE TITLE
add support for Hyundai IONIQ Hybrid and PlugIn Hybrid

### ISSUE THREAD

**Issue by GPlay97** [EVNotify/EVNotify#53]
modify state of charge command and it's calculation to add support for Hyundai IONIQ Hybrid and Hyundai IONIQ PlugIn Hybrid. They are using the BMS SoC instead of the Display SoC command.

This also requires to set the car in the settings.

**Comment by SebRut** [comment]
Is it possible to help for extended support of the PlugIn Hybrid?

**Comment by SebRut** [comment]
Could this data help? https://github.com/JejuSoul/OBD-PIDs-for-HKMC-EVs/tree/master/Ioniq%20PHEV%20-%208.9kWh

**Comment by GPlay97** [comment]
As mentioned now in the README, v3 will be the next generation to be able to handle more cars and more features, so this will be closed here for now
