### ISSUE TITLE
Add 12V battery voltage watchdog

### ISSUE THREAD

**Issue by vbartels** [EVNotify/EVNotify#73]
To avoid an empty 12V Battery I had the Idea of an voltage watchdog.
The 12V voltage can be read out via OBD, too.  If it drops under a certain value (settings?) it activates the dongles standby mode.

Additional features could be:
*push notifiy/telegram message if voltage dropped
*/12v command to get the value via telegram bot
*/12vwatchdog command to get informations about the watchdogs activation state and voltage value.
*/won to activate the watchdog
*/woff to deactivate watchdog (and wake up the dongle from standby)
*12V Voltage display on the App itself

This would be very useful if you have a dedicated phone in the car wich (almost) never leaves the cabin. So you dont have to worry about your obd dongle sucking the 12v battery empty.

**Comment by SebastianDietrich** [comment]
This would be extremely useful for most users. Currently **remote** monitoring (as stated prominently on the website) does not work (since the data will not update when the car is turned off).

**Comment by GPlay97** [comment]
If Car is off, it is impossible to retrieve data.

The watchdog is just a mechanism to auto start EVNotify if car is turned on again, without touching the app.

**Comment by GPlay97** [comment]
Remote monitoring is working.

What are you struggling with?

**Comment by noradtux** [comment]
@SebastianDietrich @vbartels 
Once the car has powered off you will not get any data from it.
Have a look at this: https://github.com/noradtux/evnotipi-watchdog
It is an extended version of the original watchdog which can also be read through i2c. I use it extensively.

**Comment by SebastianDietrich** [comment]
Hmm - in my case (KIA e-Niro) it still sends data when powered off, but stops when I leave the car:
* I turn off the car (still sitting in the car) --> everything works fine.
* I leave the car and plug it in, car starts charging --> everything still works fine.
* I lock the car (from outside) --> I do no longer get infos.
This could of course be the fault of my phone - the screen goes dark after a minute.

Is this the desired behavior? If so, how would remote monitoring work? If not, what could be my problem and how long should it last (until charging ends or until car is unplugged)?

**Comment by mhantsch** [comment]
@SebastianDietrich My guess is EVNotify gets killed by your Android. Make sure you have disabled all battery optimisation settings for EVNotify in Android. It depends on your version of Android and your phone manufacturer how this is done.

As long as EVNotify is kept running and not killed by Android, it will read data from the Dongle and send it to the cloud until charging is finished. When it no longer receives any new data, eventually it will instruct the Dongle to enter a low-power sleep mode and turn itself to sleep state too.

**Comment by SebastianDietrich** [comment]
@mhantsch - you could be right - since I turned on "Bildschirm aktiv lassen" it runs until charging is finished.

**Comment by GPlay97** [comment]
Implemented longer time ago.
